name = "vidnav"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next/standalone"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liZBRHtzydQyiSV5"
GITHUB_OWNER = "tianyaxiang"
GITHUB_REPO = "vidnav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://vid.newkit.site/api/auth"
NEXT_PUBLIC_API_URL="https://vid.newkit.site"

